### PR TITLE
fix date and time error when fetching comments.

### PR DESCRIPTION
**Pull request by KorigamiK**
Its a simple fix and everything works fine now.
Maybe the youtube date format had changed?

### CODE REVIEW

**Comment by otisdog8** [comment]
Could you merge it into here?
https://github.com/otisdog8/termitube/
I'm making a fork because the repository is mostly unmaintained

**Comment by KorigamiK** [comment]
This sounds good. I'll do that as soon as I get time. I've actually made a lot of changes to fixes many broken aspects of this app but never bothered to make a pull request.

**Review by KorigamiK — COMMENTED** [review]
Cool

**Comment by iamtalhaasghar** [comment]
Fetching comments functionality was broken when I removed Youtube API. Perhaps we can work on that first.

**Pull request closed without merging**
